version: 0.2
phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn clean package shade:shade
artifacts:
  files:
    - /codebuild/output/*/src/getCustomerInfo-1.0-SNAPSHOT-shaded.jar

