version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file GetCustomerInfo::template.yml --s3-bucket sax-getci --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yml
    - outputSamTemplate.yaml
