version: 0.1
phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
artifacts:
  files:
    - target/getCustomerInfo-1.0-SNAPSHOT-shaded.jar
  discard-paths: yes