version: 0.1
phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
  post_build:
    commands:
      - ls ./target
      - aws s3 cp ./target/getCustomerInfo-1.0-SNAPSHOT.jar s3://sax-deploy/getCustomerInfo-1.0-SNAPSHOT-shaded.jar
artifacts:
  files:
    - samTemplate.yaml
  discard-paths: yes