version: 0.1
phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
  post_build:
    commands:
      - ls
artifacts:
  files:
    - target/getCustomerInfo-1.0-SNAPSHOT.jar
  discard-paths: yes