version: 0.1
phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
  post_build:
    commands:
      - aws s3 target/getCustomerInfo-1.0-SNAPSHOT-shaded.jar s3://sax-deploy/getCustomerInfo-1.0-SNAPSHOT-shaded.jar
artifacts:
  type: zip
  files:
    - samTemplate.yaml
  discard-paths: yes