AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  getCustomerInfo:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: sax.lab.aws.lambda.GetCustomerInfoHandler
      Runtime: java8
      CodeUri: codepipeline-eu-west-1-378798684257/getCustomerInfoPipel/MyAppBuild/getCustomerInfo-1.0-SNAPSHOT-shaded.jar
      Description: ''
      MemorySize: 512
      Timeout: 15
      Role: 'arn:aws:iam::028186001988:role/service-role/readRole'
    Metadata:
      Version: 1.0